### PR TITLE
Fix WorkloadEntry json

### PR DESCRIPTION
**Pull request by shanchunyang0919**
### Why?
Kubernetes controller-runtime client is not able to fetch `WorkloadEntry` object's metadata and spec

### CODE REVIEW

**Comment by shanchunyang0919** [comment]
Will this change affect any `istio-operator` repo related stuff by any chance?

**Comment by shanchunyang0919** [comment]
@Laci21, will this change affect any existing `istio-operator` related stuff?

**Review by turip — APPROVED** [review]

**Comment by Laci21** [comment]
> @Laci21, will this change affect any existing `istio-operator` related stuff?

No, it should be fine, thanks for checking!

**Comment by shanchunyang0919** [comment]
Thanks @Laci21.

**Pull request merged**
